# Generated by Django 4.2 on 2023-05-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0026_remove_composteur_gsm_composteur_nb_gsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='composteur',
            name='password',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
