# Generated by Django 4.2 on 2023-05-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0027_composteur_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composteur',
            name='composteur_id',
        ),
        migrations.RemoveField(
            model_name='composteur',
            name='password',
        ),
    ]
