# Generated by Django 4.2 on 2023-05-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0028_remove_composteur_composteur_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='comp',
        ),
        migrations.AddField(
            model_name='projet',
            name='composteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='registre.composteur'),
        ),
    ]
