# Generated by Django 4.2 on 2023-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0030_remove_projet_composteur_projet_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='composteur',
            name='composteur_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='composteur',
            name='password',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
