# Generated by Django 4.2 on 2023-05-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0032_remove_composteur_composteur_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='comp',
        ),
        migrations.AddField(
            model_name='composteur',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registre.projet'),
        ),
    ]
