# Generated by Django 4.2 on 2023-05-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0033_remove_projet_comp_composteur_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='start_date',
        ),
    ]
