# Generated by Django 4.2 on 2023-05-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0034_remove_projet_end_date_remove_projet_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composteur',
            name='projet',
        ),
    ]
