# Generated by Django 4.2 on 2023-05-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registre', '0035_remove_composteur_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='composteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registre.composteur'),
        ),
    ]
