# Generated by Django 4.2 on 2023-05-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='map.nodes'),
        ),
    ]
