# Generated by Django 4.2 on 2023-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_post_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='référence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
